spring:
  datasource:
    username: ENC(AWpskahhSYzUEHh76454wg==)
#    username: root
    password: ENC(O3ibdCQRZVmaB/vmCLSpDHzDpNRyl6rS)
#    password: root  
    url: jdbc:mysql://localhost:3306/javatechie
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect




